### ISSUE TITLE
Bug with matching/key replacement

### ISSUE THREAD

**Issue by ia-chyde** [apideck-libraries/portman#672] opened 2024-11-01 15:36 UTC
In v1.30.5 a bug was introduced with matching values. Pinning my portman version to 1.30.4 fixes the issue.
ATTN: @thim81 

This is the OAS value being replaced - but in 1.30.5 it is replacing in some areas with the example, but in other areas it's replacing properly with the overridden value.
<img width="494" alt="image" src="https://github.com/user-attachments/assets/09ef8cfa-1041-4d4b-aa18-283dc3e1771e">

Example fail from html report:
<img width="1035" alt="image" src="https://github.com/user-attachments/assets/9a81f24b-2637-4d91-a888-4a1eab30567a">

Example of replacement setup from the portman config:
<img width="591" alt="image" src="https://github.com/user-attachments/assets/18bb173e-dae3-467d-a5a7-055851c87faa">

**Comment by thim81** [comment] 2024-11-01 15:43
hi @ia-chyde 

We did improve some [matching logic and added additional tests](https://github.com/apideck-libraries/portman/pull/669/files), so it seems to have caused some side-effects.

I'll look into it and add a test to cover this.

**Comment by thim81** [comment] 2024-11-01 16:14
hi @ia-chyde 

Could you share the OpenAPI path (only the path is sufficient)? So we can run some manual validations?

**Comment by ia-chyde** [comment] 2024-11-01 16:27
`/workspace/portman/OASfromAPI.json` (in a jenkins agent workspace)

**Comment by thim81** [comment] 2024-11-01 16:35
hi @ia-chyde 

We have a [PR](https://github.com/apideck-libraries/portman/pull/673) ready that should fix the reported issue.

The input
```
paths:
  /licenses/{licenseKey}/modules:
    delete:
      summary: Delete a license module
      operationId: deleteLicenseModule
      parameters:
        - $ref: '#/components/parameters/licenseKey'
        - name: modules
          in: query
          description: List of modules to delete, separated by commas
          required: true
          schema:
            type: string
            example: com.inductiveautomation.perspective,com.inductiveautomation.sqlbridge
      responses:
        '204':
          description: No Content - Successfully deleted the license module
        '400':
          description: Bad Request - Invalid license key or parameters
        '404':
          description: Not Found - License key not found
components:
  parameters:
    licenseKey:
      name: licenseKey
      in: path
      required: true
      description: The license key of the license
      schema:
        type: string
        minLength: 8
        example: хххххххХ
```

with the targeting

```
"overwrites": [
    {
      "openApiOperation": "DELETE::/licenses/{licenseKey}/modules*",
      "overwriteRequestPathVariables": [
        {
          "key": "licenseKey",
          "value": "{{licenseKey}}"
        }
      ]
    }
  ]
```

results in:
<img width="922" alt="image" src="https://github.com/user-attachments/assets/ec7480d5-0b99-4da8-b7f4-e15e61fd5031">

**Comment by thim81** [comment] 2024-11-01 17:14
hi @ia-chyde 

We just release version 1.30.6 which should handle your reported issue.
If this solves your issue, feel free to close this.

If not, please provide more info so we can reproduce it and look further for a fix.

**Comment by ia-chyde** [comment] 2024-11-01 18:54
Still one bug. Now there is a queryparam that's failing to replace. Seems it's not appending the query param to the URL:
<img width="1042" alt="image" src="https://github.com/user-attachments/assets/73a240b6-bb18-4105-9e6c-a64e40e604d9">

Definition in OAS:
<img width="1079" alt="image" src="https://github.com/user-attachments/assets/c40c73f2-ec9c-4df4-ad40-90e3a7db1ac7">

**Comment by thim81** [comment] 2024-11-01 19:56
How does the Portman config looks like?

**Comment by ia-chyde** [comment] 2024-11-01 20:02
sorry, meant to include that 
<img width="318" alt="image" src="https://github.com/user-attachments/assets/446cb234-f124-477d-8934-60029bccb7c1">

**Comment by thim81** [comment] 2024-11-01 20:56
hi @ia-chyde 

This is the result, so it looks like it is working?

<img width="1357" alt="image" src="https://github.com/user-attachments/assets/cbbdabea-66d6-41e1-8740-4a847ee8b476">

OpenAPI spec:

```
openapi: 3.0.3
info:
  title: 672 - License API2
  version: 1.0.0

paths:
  /licenses:
    get:
      summary: Get licenses
      description: |
        Returns a list of licenses that match the specified query. Valid query should either be origin and nativeId, or be licenseKeys.
      security:
        - GeneralRO: []
        - GeneralRW: []
      parameters:
        - in: query
          name: origin
          description: The origin of the license owner
          schema:
            $ref: '#/components/schemas/Origin'
          required: false
        - in: query
          name: nativeId
          description: The native ID of the license owner within the origin system
          schema:
            $ref: '#/components/schemas/NativeId'
          required: false
        - in: query
          name: licenseKeys
          description: Comma-separated list of one or more licenseKeys
          schema:
            type: string
            minLength: 1
          required: false
      responses:
        '200':
          description: No Content - Successfully deleted the license module
        '400':
          description: Bad Request - Invalid license key or parameters
        '404':
          description: Not Found - License key not found

components:
  schemas:
    Origin:
      type: string
      example: "example-origin"
    NativeId:
      type: string
      example: "example-native-id"
```

Portman config:
```
{
  "globals": {
    "stripResponseExamples": true
  },
  "overwrites": [
    {
      "openApiOperation": "GET::/licenses",
      "overwriteRequestQueryParams": [
        {
          "key": "licenseKeys",
          "value": "{{licenseKey}}",
          "disable": false,
          "overwrite": true
        }
      ]
    }
  ],
  "version": 1
}

```

**Comment by ia-chyde** [comment] 2024-11-02 15:09
This is from the postman-generated collection. You can see it is not putting the path param in the request, and on the previous version, it was
<img width="1160" alt="image" src="https://github.com/user-attachments/assets/1c843325-a95c-4731-b7f4-fafbfb244a9f">

**Comment by thim81** [comment] 2024-11-03 10:15
hi @ia-chyde 

I used the following:

OpenAPI
```
openapi: 3.0.0
info:
  title: 672 - License API2
  version: 1.0.0

paths:
  /licenses:
    get:
      summary: Get licenses
      description: |
        Returns a list of licenses that match the specified query. Valid query should either be origin and nativeId, or be licenseKeys.
      security:
        - GeneralRO: []
        - GeneralRW: []
      parameters:
        - in: query
          name: origin
          description: The origin of the license owner
          schema:
            $ref: '#/components/schemas/Origin'
          required: false
        - in: query
          name: nativeId
          description: The native ID of the license owner within the origin system
          schema:
            $ref: '#/components/schemas/NativeId'
          required: false
        - in: query
          name: licenseKeys
          description: Comma-separated list of one or more licenseKeys
          schema:
            type: string
            minLength: 1
          required: false
      responses:
        '200':
          description: No Content - Successfully deleted the license module
        '400':
          description: Bad Request - Invalid license key or parameters
        '404':
          description: Not Found - License key not found
  /licenses/{licenseKey}:
    get:
      summary: Get a single license
      description: Returns a single license by licenseKey.
      security:
        - GeneralRO: []
        - GeneralRW: []
      parameters:
        - in: path
          name: licenseKey
          description: The key of the license to retrieve
          schema:
            type: string
            minLength: 8
            example: хххххххХ
          required: true
      responses:
        '200':
          description: No Content - Successfully deleted the license module
        '400':
          description: Bad Request - Invalid license key or parameters
        '404':
          description: Not Found - License key not found
components:
  schemas:
    Origin:
      type: string
      example: "example-origin"
    NativeId:
      type: string
      example: "example-native-id"
```

With this Portman config:

```
{
  "globals": {
    "stripResponseExamples": true
  },
  "overwrites": [
    {
      "openApiOperation": "GET::/licenses",
      "overwriteRequestQueryParams": [
        {
          "key": "licenseKeys",
          "value": "{{licenseKey}}",
          "disable": false,
          "overwrite": true
        }
      ]
    },
    {
      "openApiOperation": "GET::/licenses/*",
      "overwriteRequestQueryParams": [
        {
          "key": "licenseKeys",
          "value": "{{licenseKey}}",
          "disable": false,
          "overwrite": true
        }
      ],
      "overwriteRequestPathVariables": [
        {
          "key": "licenseKey",
          "value": "{{licenseKey}}"
        }
      ]
    }
  ],
  "version": 1
}

```

Results in:

<img width="928" alt="image" src="https://github.com/user-attachments/assets/0a8c3b59-3153-4864-9ae4-bcda43dd5743">

<img width="923" alt="image" src="https://github.com/user-attachments/assets/4feade49-208f-49dd-b85f-cd41cbba587a">

What did you had in your Portman Config?

**Comment by ia-chyde** [comment] 2024-11-04 12:59
> hi @ia-chyde
> 
> I used the following:
> 
> OpenAPI
> 
> ```
> openapi: 3.0.0
> info:
>   title: 672 - License API2
>   version: 1.0.0
> 
> paths:
>   /licenses:
>     get:
>       summary: Get licenses
>       description: |
>         Returns a list of licenses that match the specified query. Valid query should either be origin and nativeId, or be licenseKeys.
>       security:
>         - GeneralRO: []
>         - GeneralRW: []
>       parameters:
>         - in: query
>           name: origin
>           description: The origin of the license owner
>           schema:
>             $ref: '#/components/schemas/Origin'
>           required: false
>         - in: query
>           name: nativeId
>           description: The native ID of the license owner within the origin system
>           schema:
>             $ref: '#/components/schemas/NativeId'
>           required: false
>         - in: query
>           name: licenseKeys
>           description: Comma-separated list of one or more licenseKeys
>           schema:
>             type: string
>             minLength: 1
>           required: false
>       responses:
>         '200':
>           description: No Content - Successfully deleted the license module
>         '400':
>           description: Bad Request - Invalid license key or parameters
>         '404':
>           description: Not Found - License key not found
>   /licenses/{licenseKey}:
>     get:
>       summary: Get a single license
>       description: Returns a single license by licenseKey.
>       security:
>         - GeneralRO: []
>         - GeneralRW: []
>       parameters:
>         - in: path
>           name: licenseKey
>           description: The key of the license to retrieve
>           schema:
>             type: string
>             minLength: 8
>             example: хххххххХ
>           required: true
>       responses:
>         '200':
>           description: No Content - Successfully deleted the license module
>         '400':
>           description: Bad Request - Invalid license key or parameters
>         '404':
>           description: Not Found - License key not found
> components:
>   schemas:
>     Origin:
>       type: string
>       example: "example-origin"
>     NativeId:
>       type: string
>       example: "example-native-id"
> ```
> 
> With this Portman config:
> 
> ```
> {
>   "globals": {
>     "stripResponseExamples": true
>   },
>   "overwrites": [
>     {
>       "openApiOperation": "GET::/licenses",
>       "overwriteRequestQueryParams": [
>         {
>           "key": "licenseKeys",
>           "value": "{{licenseKey}}",
>           "disable": false,
>           "overwrite": true
>         }
>       ]
>     },
>     {
>       "openApiOperation": "GET::/licenses/*",
>       "overwriteRequestQueryParams": [
>         {
>           "key": "licenseKeys",
>           "value": "{{licenseKey}}",
>           "disable": false,
>           "overwrite": true
>         }
>       ],
>       "overwriteRequestPathVariables": [
>         {
>           "key": "licenseKey",
>           "value": "{{licenseKey}}"
>         }
>       ]
>     }
>   ],
>   "version": 1
> }
> ```
> 
> Results in:
> 
> <img alt="image" width="928" src="https://private-user-images.githubusercontent.com/952446/382562780-0a8c3b59-3153-4864-9ae4-bcda43dd5743.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3MjU0MjcsIm5iZiI6MTczMDcyNTEyNywicGF0aCI6Ii85NTI0NDYvMzgyNTYyNzgwLTBhOGMzYjU5LTMxNTMtNDg2NC05YWU0LWJjZGE0M2RkNTc0My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNFQxMjU4NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NjBiNjQ5MTgwNDdiOGFjNDI2ZjZkYzcwMDgwYmI4ZjIyMjJjMmM0NDM3MDFjOTYzYTM3YTk1YzQyNGM2ODVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Kw0mUp6ZOUiZcGjBFPS0pBJl1mW-ZHjNgM4VfpcdNsk"> <img alt="image" width="923" src="https://private-user-images.githubusercontent.com/952446/382562797-4feade49-208f-49dd-b85f-cd41cbba587a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3MjU0MjcsIm5iZiI6MTczMDcyNTEyNywicGF0aCI6Ii85NTI0NDYvMzgyNTYyNzk3LTRmZWFkZTQ5LTIwOGYtNDlkZC1iODVmLWNkNDFjYmJhNTg3YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNFQxMjU4NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNWM1MzJhYjBhZDFmYTdkMzU0YTAzNDkwNTc0NWU4ZWYyMDQyNWRlZWZlMDIyZWM3NjE4ZTBhYTdiNjgwN2JiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.-NfM9KX_vdtGyfvDdeTxiJpxeE54gls_jZo4uVI0eyk">
> What did you had in your Portman Config?

https://github.com/apideck-libraries/portman/issues/672#issuecomment-2452510774 from above - I see you also had one replacing for `/*` - I don't have this and before your changes, it was not necessary.

**Comment by thim81** [comment] 2024-11-04 19:06
Did you not had a * in the openApiOperation?

![image](https://github.com/user-attachments/assets/96e9b42d-2efb-4db9-b929-3d62b76b30f3)

**Comment by ia-chyde** [comment] 2024-11-04 19:11
that's right. only that one entry you see. Worked fine in previous version.

**Comment by thim81** [comment] 2024-11-04 19:42
Hmm 🤔 that should not have worked for "/licenses/..." since there was no * wildcard character involved.

I have a PR that will allow "GET: :/licenses*" would you be OK with that?

**Comment by ia-chyde** [comment] 2024-11-04 20:43
sure, I could make a config update. I figured that might have been a bug
too :-)

**Comment by thim81** [comment] 2024-11-05 18:56
hi @ia-chyde 

We just release [version v1.30.7](https://github.com/apideck-libraries/portman/releases/tag/v1.30.7), could you give a try?
You will have to update "openApiOperation": "GET::/licenses*" by adding an ending *

**Comment by ia-chyde** [comment] 2024-11-06 19:29
seems to work well. I'll let you know if anything else comes up, but I
think you can close this defect.

**Closed** 2024-11-06 19:31 UTC
Labels: bug

**Comment by thim81** [comment] 2024-11-06 21:58
@ia-chyde Thanks for the patience and the assistance during the validation
