### ISSUE TITLE
orderOfOperations causes error `UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'sort' of undefined`

### ISSUE THREAD

**Issue by whorst** [apideck-libraries/portman#236] opened 2022-01-14 02:29 UTC
**Describe the bug**
I added orderOfOperations to my config file, and the program errors out around line 22 of orderCollectionRequests.js

**To Reproduce**
1. After setting up my config file and cli file (which I will attach here) I run:  
`portman -t variationTests --cliOptionsFile portman/portman-cli.json`
2. The error message I've described is displayed to me
[portman copy.zip](https://github.com/apideck-libraries/portman/files/7867216/portman.copy.zip)

**Screenshots**
<img width="1491" alt="Screen Shot 2022-01-13 at 9 21 41 PM" src="https://user-images.githubusercontent.com/13001266/149440581-238a4c6e-21d2-406a-a024-0a31f4b66477.png">

**Comment by thim81** [comment] 2022-01-14 10:56
Update:
The "orderOfOperations" was initially focussed on sorting requests in folders, while your collection has a great number of request on "root" level.

Based on your collection, we are working on a PR to include to the sorting on root level, next to the folder sorting.

**Comment by whorst** [comment] 2022-01-14 13:34
@thim81 what would be an example of sorting requests in folders? Would it be like there were multiple openapi.yaml files spread over multiple folders?

**Comment by thim81** [comment] 2022-01-14 14:09
@whorst in OpenAPI you can define "tags" to group requests. On conversion from OpenAPI to Postman, you can have to option to group them in "folders".

Have a look at https://github.com/apideck-libraries/portman/tree/main/examples/cli-filtering
![image](https://user-images.githubusercontent.com/952446/149528184-9bcf7608-3fde-44f3-8a10-e2b726eb70f6.png)

By default Portman groups them by `tags`, since we are using the `"folderStrategy": "Tags"` https://github.com/apideck-libraries/portman/blob/main/postman-config.default.json

Another strategy could by "Paths": `"folderStrategy": "Paths"`

**Comment by thim81** [comment] 2022-01-16 14:21
@whorst The PR is merged and a fix will be part of the next release of Portman.

**Comment by whorst** [comment] 2022-01-16 23:08
@thim81 thank you! You guys are awesome, best of luck!

**Comment by thim81** [comment] 2022-01-17 19:35
@whorst We just release Portman 1.13.1, which should contain a fix for the orderOfOperations. Please report back if the issue is not resolved.

**Closed by thim81** 2022-01-17 19:35 UTC
Labels: bug
