### ISSUE TITLE
Duplicate tests created for each tag on an operation

### ISSUE THREAD

**Issue by yelob** [apideck-libraries/portman#399] opened 2022-09-07 17:39 UTC
When generating tests, if a path in the OAS schema has more than one tag, multiple, duplicate tests are created by Portman, one for each tag.

Is this functioning as designed? I can provide schemas/configs to reproduce the issue if this is indeed a defect. If not, is there some way to disable this behavior?

Thanks!

**Comment by thim81** [comment] 2022-09-07 18:38
Hi @yelob 

This is the 1st time we hear about this issue.

Could you indeed share an OAS and your Portman config, so we can reproduce the behaviour?

**Comment by yelob** [comment] 2022-09-07 19:01
Yep, no problem.

Attached you will find two schemas; one with a single tag for the path, and another with multiple tags. I've also attached the portman-config file and the resultant postman collections.

Let me know if you need any more info.

Thanks!
[temp-portman-config.txt](https://github.com/apideck-libraries/portman/files/9508915/temp-portman-config.txt)
[temp-schema-multiple-tags.txt](https://github.com/apideck-libraries/portman/files/9508916/temp-schema-multiple-tags.txt)
[temp-schema-single-tag.txt](https://github.com/apideck-libraries/portman/files/9508917/temp-schema-single-tag.txt)
[postman-multiple-tags.txt](https://github.com/apideck-libraries/portman/files/9508918/postman-multiple-tags.txt)
[postman-single-tag.txt](https://github.com/apideck-libraries/portman/files/9508919/postman-single-tag.txt)

**Comment by tillig** [comment] 2022-09-07 19:13
If I had to guess, it's the `openapi-to-postman` library, where [the `folderStrategy` can be set to `paths` or `tags`](https://github.com/postmanlabs/openapi-to-postman/blob/develop/OPTIONS.md).  Portman currently relies on v2.14.1 of that library. I haven't dug into it, but there [do appear to be some older issues](https://github.com/postmanlabs/openapi-to-postman/issues?q=is%3Aissue+folderstrategy+is%3Aclosed) around that configuration value, some of which may be resolved by updating to the latest (4.1.1).

**Comment by thim81** [comment] 2022-09-16 21:54
hi @yelob 

The input from @tillig is completely correct.
The openapi-to-postman library, which is being used in Portman, uses the "tags" as folders and puts all the requests linked to tags, in their folder.

folderStrategy = `Tags`
<img width="278" alt="2022-09-16 at 23 48 00@2x" src="https://user-images.githubusercontent.com/952446/190800885-d1750cec-fb77-45b7-a8c9-6df8bc77f7e1.png">

vs 

folderStrategy = `Paths`
<img width="283" alt="2022-09-16 at 23 50 17@2x" src="https://user-images.githubusercontent.com/952446/190801807-7ece4b4f-b828-42a7-93b5-fa1817ec3740.png">

I'm afraid we cannot solve this issue, since even we would patch the openapi-to-postman library which tag aka folder should we keep? 
You could reduce the "tags" that you don't want.

**Comment by tillig** [comment] 2022-09-16 22:33
Is there a way to take the upgraded version of the library? As noted, there have been a lot of changes in that library to fix things up... and I think the default folder strategy in the latest version _is paths_ which would solve the problem.

**Comment by thim81** [comment] 2022-09-17 07:10
Hi @tillig 

You can use the parameter to pass along the "--postmanConfigFile" which will allow you to define your own openapi-to-postman conversion options, like

```
{
  "folderStrategy": "Paths",
  "requestParametersResolution": "Example",
  "exampleParametersResolution": "Example"
}
```

**Comment by thim81** [comment] 2022-09-20 19:03
@tillig @yelob We are going to close this item, since there is an option to use the `"folderStrategy": "Paths"` as conversion.

The multiple tags is actual expected behaviour.

**Closed by thim81** 2022-09-20 19:03 UTC

**Comment by yelob** [comment] 2022-09-20 19:21
Ok, sounds good, but I'm curious what your use-case is for wanting a duplicate test generated for each tag.

**Comment by thim81** [comment] 2022-09-20 20:04
OpenAPI is a specification format used for specifying API operations, so the tags serve for grouping/tagging operations for documentation purpose.

Postman is a API execution tool, but it has no tagging option, instead they do offer folders for grouping requests.

So when the OpenAPI doc is converted into a Postman collection, the tags are used to create folders, to allow the grouping of requests.

So the use-case for the conversion = grouping/structuring requests
The use-case for Postman = grouped execution

Since during the conversion, it starts with the request and these get inserted in the folders. It applies that the request (that is tagged with multiple tags) belongs in multiple folders. 
During the execution of a Postman collection in the App or in Newman CLI, you can define which "folder" to execute.
It could be that you tag your requests per operation (CREATE/UPDATE) and each request also with the entities (Users, Orders, ...), resulting in folders: CREATE, UPDATE, Users,Orders, ...
This will allow you to keep 1 Postman collection but execute all the CREATE operations in a run or if you only want to execute all the order entity "Users" operations.
