### ISSUE TITLE
oaOutput in NPX call doesn't write file

### ISSUE THREAD

**Issue by ChristineP2** [apideck-libraries/portman#278] opened 2022-03-12 04:48 UTC
I attempted to generate an output and an oaOutput file together using `npx` using Gradle.  The CLI output indicated the oaOutput file wrote to tmp even though I ensured the filepath existed prior to running the command.

I will say I find it is just as easy to chain a gradle task for [OpenAPI-format](https://github.com/thim81/openapi-format) with the Portman task. I wonder if it might make sense to avoid embedding it, unless it is needed for other purposes.

My current plan is to create the various test sets from my main spec using openAPI-format, then process that through portman to generate the postman collection(s).

**Comment by thim81** [comment] 2022-03-12 08:50
Hi @ChristineP2 

Could you share which parameters you were using? So we can reproduce the issue.

**Comment by thim81** [comment] 2022-03-12 09:32
We integrated OpenApi-format to facilitate easy filtering capabilities using a wide range of options (tags, tag values, targeting syntax (ex: POST::*)) without the need for Portman users to install an additional package. 

For more complex usage scenarios, you can use OpenApi-format upfront and pass the result to Portman. We use similar chaining of OpenApi-format and Portman, where we have a huge OpenApi spec but want to test parts individually or filter out WIP endpoints from the test suite.

**Comment by ChristineP2** [comment] 2022-03-14 17:39
The chain is what I ended up doing as well.  I loved the initial filtering capability, but there's even more I can do with the full library.  Overall I'm thrilled with these 2 libraries, they make OAS the functional and time saving spec I expected it to be.  Without these tools, it makes keeping the OAS3 file up to date a chore instead of a needed tool.  I am so happy to have these. 

I'm going to work on getting a POC together and see if I can find root cause on the underlying issue.

**Comment by thim81** [comment] 2022-03-21 09:58
@ChristineP2 Do you have any news on which parameters you were using, so we can reproduce the issue?

**Comment by ChristineP2** [comment] 2022-03-22 19:25
@thim81 Sorry for the delay.  I put this branch together that will hopefully allow you to see what I'm seeing: https://github.com/ChristineP2/swagger-petstore/tree/portman

I believe it will demonstrate 2 issues:

1. oaOutput doesn’t seem to save the filter (most visible when not saving the postman collection)
2. The command errs if you don’t create the directories yourself prior to running the cli.

The command with the collection and filter is `npx @apideck/portman --local src/main/resources/openapi.yaml --collectionName test-save-filter --filterFile filterby.json --oaOutput src/gen/portman/openapi-filtered.yaml --output src/gen/portman/testCollection.json`

The command with just the filter output is where I saw the tmp location: `npx @apideck/portman --local src/main/resources/openapi.yaml --collectionName test-save-filter --filterFile filterby.json --oaOutput src/gen/portman/openapi-filtered.yaml`

You can also run the following gradle tasks:

`./gradlew testPortmanFilterOnly` - This results in the output with the .tmp file listed and no files created.

`./gradlew testPortman` - This results in the collection displaying, but no filter file added.

`./gradlew testPortmanNoDir` - This results in a hard error as the directories haven’t been created

**Comment by thim81** [comment] 2022-03-25 12:28
@ChristineP2 What is the path that you run:

`npx @apideck/portman --local src/main/resources/openapi.yaml --collectionName test-save-filter --filterFile filterby.json --oaOutput src/gen/portman/openapi-filtered.yaml --output src/gen/portman/testCollection.json`

You run it from from the content root or from `src/main/resources/`? Because Portman threats all input files as relative from where the command is initiated.

I'll investigate if Portman will create the folder for oaOutput, since that might be a bug.

**Comment by thim81** [comment] 2022-03-28 17:45
@ChristineP2 We just released version 1.15.0 of Portman, where the reported issues should be fixed.

**Comment by thim81** [comment] 2022-03-28 17:46
Closing this issue. If you still have problems, feel free to re-open or create a new issue.

**Closed by thim81** 2022-03-28 17:46 UTC
Labels: question
