### ISSUE TITLE
Problem with bool variable setted by pre-request script

### ISSUE THREAD

**Issue by jdevosMagento** [apideck-libraries/portman#286] opened 2022-03-22 17:57 UTC
I have a new problem.

This time, it is the use of a variable defined by a prerequest script and boolean type.

My API documentation:

```
attribute_1:
           type: boolean
           example: true
```

My overwriteRequestBody:

```
{
             "key": "data[0].attribute_1",
             "value": "{{attribute_1_value}}",
             "overwrite": true
},
```

I am forced to define value as a string, otherwise the json is invalid and portman shows json format error.

But by doing this, it integrates the attribute as a string also in postman and the call is therefore in failure because the API expects a boolean and not a string.

Postman:
```
"data": [
{
     "attribute_1": "{{attribute_1_value}}"
}
```

The API normally expects: (without quotes)
```
"data": [
{
     "attribute_1": {{attribute_1_value}}
}
```

I think it would be necessary, when generating the postman collection, to check if value is a variable and if so, cast according to a "type" attribute for example

**Comment by thim81** [comment] 2022-03-22 18:09
Hi @jdevosMagento 

We have support for "{{$randomInt}}" which gets converted into number (not a string).
I'll have to investigate how the booleans are handled, in combination with {{postman_variables}}

**Comment by thim81** [comment] 2022-03-23 07:09
@jdevosMagento What do you think about this proposal:

Postman Variable: marco_polo (which is a Boolean or Number, not string) is used like {{marco_polo}}
If you define the variable in an overwrite in Portman, you would set it like "{{{marco_polo}}}" surrounded by 3x {{{ and 3x }}}. 
Portman can use this to detect the variable as a non-string variable and converts it into {{marco_polo}} with " with only 2x {{}} making it a valid Postman variable. 

I ll still explore type detection based on OpenApi but this {{{}}} syntax allows the users to indicate a non-string type manually.

Cc @nicklloyd, what is your opinion?

**Comment by jdevosMagento** [comment] 2022-03-23 09:33
Hello @thim81 yes sounds good to me!

Otherwise why not add a "type" variable when you want to force the type : 

```
{
             "key": "data[0].attribute_1",
             "value": "{{attribute_1_value}}",
             "type": "boolean"
             "overwrite": true
},
```

In this case, if "type" is specified portman uses this value to define how it should return the data.

But your proposal seems just as good

**Comment by thim81** [comment] 2022-03-23 09:40
Hi @jdevosMagento,

I thought about the "type" setting option, but that would mean more configuration and complexity for the Portman users to learn and setup, while the goal is always to facilitate easy configuration of Portman but with enough flexibility.

The {{{}}} provides the control by using an "escape" syntax, where you tell Portman to escape the "string" type and use it as a raw type. 

I'll turn this into a feature request and see when there is time to introduce the feature.

**Comment by jdevosMagento** [comment] 2022-03-23 09:45
It's perfect, thank you

**Comment by thim81** [comment] 2022-03-25 12:15
@jdevosMagento The PR is ready and will be reviewed.

An example of the result of the conversion with the escaped number/boolean types.

```json
"overwrites": [
    {
      "openApiOperation": "*::/*",
      "overwriteRequestBody": [
        {
          "key": "data[0].key_1",
          "value": "{{attributeString}}",
          "overwrite": true
        },
        {
          "key": "data[0].key_2",
          "value": "{{{attributeNumber}}}",
          "overwrite": true
        },
        {
          "key": "data[0].key_3",
          "value": "{{{attributeBoolean}}}",
          "overwrite": true
        },
        {
          "key": "data[0].key_4",
          "value": "Marco Polo {{attributeNumber}}",
          "overwrite": true
        },
        {
          "key": "data[1]",
          "remove": true
        }
      ]
    }
  ]
```

![2022-03-25 at 13 13 07@2x](https://user-images.githubusercontent.com/952446/160118812-1f8577f5-9270-4555-a620-566aca093b70.png)

**Comment by jdevosMagento** [comment] 2022-03-25 14:01
It's great the result is perfect, thank you for the efficiency!

**Comment by thim81** [comment] 2022-03-28 17:45
@jdevosMagento We just released version 1.15.0 of Portman, where this enhancement is included.
Closing this issue.

**Comment by jdevosMagento** [comment] 2022-03-29 11:33
Hello, i think there is a problem when using variationTests and overwriteRequestBody 

`{
    "overwrites": {
        "openApiOperationId": "Xxxx",
        "overwriteRequestBody": [
            {
                "key": "data[0].yyy",
                "value": "{{yyy}}",
                "overwrite": true
            },
            {
                "key": "data[0].xxx",
                "value": "{{{xxx}}}",
                "overwrite": true
            }
        ]
    },
    "variationTests": {
        "openApiOperationId": "Xxxx",
        "variations": [
            {
                "name": "BadRequest",
                "openApiResponse": "400",
                "overwrites": [
                    {
                        "overwriteRequestBody": [
                            {
                                "key": "data[0].yyy",
                                "remove": true
                            }
			]
                    }
                ],
                "tests": {
                    "contractTests": [
                        {
                            "statusCode": {
                                "enabled": true
                            },
                            "jsonBody": {
                                "enabled": true
                            },
                            "schemaValidation": {
                                "enabled": true
                            }
                        }
                    ]
                }
            },
        ]
    }
}
`

i have this error : 

`(node:3391829) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token { in JSON at position 116
    at JSON.parse (<anonymous>)
    at Object.overwriteRequestBody (/home/jdevos/.nvm/versions/node/v14.18.1/lib/node_modules/@apideck/portman/dist/application/overwrites/overwriteRequestBody.js:17:25)
    at /home/jdevos/.nvm/versions/node/v14.18.1/lib/node_modules/@apideck/portman/dist/application/overwrites/applyOverwrites.js:8:16
    at Array.map (<anonymous>)
    at Object.applyOverwrites (/home/jdevos/.nvm/versions/node/v14.18.1/lib/node_modules/@apideck/portman/dist/application/overwrites/applyOverwrites.js:6:25)
    at /home/jdevos/.nvm/versions/node/v14.18.1/lib/node_modules/@apideck/portman/dist/application/TestSuite.js:228:20
    at Array.map (<anonymous>)
    at TestSuite.injectOverwrites (/home/jdevos/.nvm/versions/node/v14.18.1/lib/node_modules/@apideck/portman/dist/application/TestSuite.js:226:22)
    at VariationWriter.injectVariations (/home/jdevos/.nvm/versions/node/v14.18.1/lib/node_modules/@apideck/portman/dist/application/VariationWriter.js:84:28)
    at /home/jdevos/.nvm/versions/node/v14.18.1/lib/node_modules/@apideck/portman/dist/application/VariationWriter.js:44:23
    at Array.map (<anonymous>)
    at VariationWriter.add (/home/jdevos/.nvm/versions/node/v14.18.1/lib/node_modules/@apideck/portman/dist/application/VariationWriter.js:25:20)
    at /home/jdevos/.nvm/versions/node/v14.18.1/lib/node_modules/@apideck/portman/dist/application/TestSuite.js:46:47
    at Array.map (<anonymous>)
    at /home/jdevos/.nvm/versions/node/v14.18.1/lib/node_modules/@apideck/portman/dist/application/TestSuite.js:43:30
    at Array.map (<anonymous>)
`

No problem without variationTests, the boolean xxx its OK

**Comment by thim81** [comment] 2022-03-29 13:13
@jdevosMagento Are you able to share the OpenAPI specification (in a private way if required)? So we can try to reproduce the issue?

**Comment by jdevosMagento** [comment] 2022-03-29 13:34
Its Ok with this ?

```
---
openapi: 3.0.3
info:
  version: "1.0.0"
  title: Xxx
  description: xxx
tags:
  - name: xxxx
    description: xxxx
paths:
/nnnnn/vvvvv:
	post:
	  operationId: xxxx
	  description: "xxxxx"
	  tags:
	    - xxxx
	  requestBody:
	    content:
	      application/json:
		schema:
			type: object
			properties:
			  data:
			    type: array
			    items:
			      type: object
			      properties:
				yyy:
				  type: string
				  example: "YYY"
				xxx:
				  type: integer
				  example: 10
			      required:
				- yyy
				- xxx
			required:
			  - data

	  responses:
	    "200":
	      description: Successful operation
	      content:
		application/json:
		  schema:
			type: object
			properties:
			  aaaa:
			    type: boolean
			    example: true
			  bbbb:
			    type: array
			    items:
			      $ref: "#/components/schemas/bbbbbb"
			  cccc:
			    type: array
			    items:
			      $ref: "#/components/schemas/cccccc"
	    "400":
	      description: 400 Bad Request
	      content:
		application/json:
		  schema:
		    $ref: "#/components/schemas/dddddddd"
```

**Comment by thim81** [comment] 2022-04-01 14:31
@jdevosMagento We have found the cause and the PR will be part of the next release.

**Comment by thim81** [comment] 2022-04-01 15:06
Portman 1.15.1 has just been released with the fix for this behaviour included.

**Closed by thim81** 2022-04-01 15:06 UTC
Labels: enhancement
