### ISSUE TITLE
orderOfOperations example not working

### ISSUE THREAD

**Issue by Giackgamba** [apideck-libraries/portman#418] opened 2022-10-24 15:30 UTC
Hi all, I'm trying to use portman for a project where I need to set ordersOfOperations. I tried adding the `orderOfOperations` key to the global portman configuration, it seemed not to be picked up. 
While trying to set up a minimum viable example I tried the example provided (in the `examples/postman-ordering` folder), but AFAICS it doesn't work either.

```
$ portman -l ./examples/postman-ordering/crm.yml -c ./examples/postman-ordering/portman-config.ordering.json
======================================================================================================================================================
 Local Path:            ./examples/postman-ordering/crm.yml
 Portman Config:        ./examples/postman-ordering/portman-config.ordering.json
 Postman Config:        postman-config.default.json
 Environment:           .env
 Inject Tests:          true
 Run Newman:            false
 Newman Iteration Data: false
 Upload to Postman:     false
======================================================================================================================================================
  ✔ Conversion successful
======================================================================================================================================================
🚀 Collection written to: ./tmp/converted/crmApi.json 🚀
======================================================================================================================================================
```
But the collection in `./tmp/converted/crmApi.json` does not match with what is reported in the example's README:

```
{
  "_": {
    "postman_id": "ccd4fd97-ef97-406e-bec9-d55c4987f9db"
  },
  "item": [
    {
      "id": "258d5112-1791-4e9d-a24d-f7d5ff8abe4c",
      "name": "Companies",
      "description": {
        "content": "",
        "type": "text/plain"
      },
      "item": [
        {
          "_": {
            "portman_operation": "GET::/crm/companies"
          },
        ...
        {
          "_": {
            "portman_operation": "POST::/crm/companies"
          },
        ...
```

Am I missing something?
```
$ portman --version
1.18.1
```

**Comment by thim81** [comment] 2022-10-29 14:49
hi @Giackgamba 

Thanks for reporting this, let us look into the example and come back to you.

The ordering of operations is always a complex case since depending on the nesting in folders the expected behavior vs the result might be off.

**Comment by thim81** [comment] 2022-11-06 13:53
hi @Giackgamba,

We updated the example since it was a bit out-dated.
We reduced also the foot-print to the OpenApi specification to keep the example more compact.

**Comment by thim81** [comment] 2022-11-06 14:04
@Giackgamba The updated example is available, feel free to give it another spin: https://github.com/apideck-libraries/portman/tree/main/examples/postman-ordering

We close this issue for now, if you run into questions or issues, feel free to create a new item.

**Closed by thim81** 2022-11-06 14:04 UTC

**Comment by Giackgamba** [comment] 2022-11-29 12:21
Thank you! I can confirm it now works, both the example and my specific scenario.
