### ISSUE TITLE
order of operations is not working as expected for DELETE methods

### ISSUE THREAD

**Issue by yajiv789** [apideck-libraries/portman#208] opened 2021-12-15 12:50 UTC
Here is my configuration :  
"globals": {
    "orderOfOperations": [
      "POST::/v1/orgs",
      "GET::/v1/orgs",
      "GET::/v1/orgs/{orgId}",
      "PUT::/v1/orgs/{orgId}",
      "PUT::/v1/orgs/{orgId}/status",
      "POST::/v1/orgs/{orgId}/users",
      "GET::/v1/orgs/{orgId}/users",
      "GET::/v2/orgs/{orgId}/users",
      "GET::/v1/orgs/{orgId}/hierarchy",
      "DELETE::/v1/orgs/{orgId}/users/{userIds}",     
      "DELETE::/v1/orgs/{orgId}"
    ]
  }

Note:
  "DELETE::/v1/orgs/{orgId}/users/{userIds}",     [  API Request Name - Remove users from an organizations ]
  "DELETE::/v1/orgs/{orgId}"                                 [  API Request Name - Delete an organization ]

In the generated collection last two endpoints are not as per the defined order.

<img width="466" alt="Screenshot 2021-12-15 at 6 19 54 PM" src="https://user-images.githubusercontent.com/18140429/146189606-deacb3c0-7ab8-4be8-8d17-5cb0e677c6e6.png">

**Comment by yajiv789** [comment] 2021-12-16 16:22
@thim81   If possible, could you please take a look at this issue.
FYI - portman version - 1.12.1
         Node       version - 12.8.1
        npm          version -  6.10.3

**Comment by thim81** [comment] 2021-12-16 17:09
@yajiv789 Would it be possible to share your OpenApi spec and Portman config? So we can use it to try to reproduce the issue.

**Comment by yajiv789** [comment] 2021-12-20 19:00
@thim81  Attached spec and portman config. 
[Archive.zip](https://github.com/apideck-libraries/portman/files/7747397/Archive.zip)

**Comment by thim81** [comment] 2021-12-21 08:48
We found the cause and the [fix](https://github.com/apideck-libraries/portman/pull/216) will be part of the next release.

This is the result after the fix:
![2021-12-21 at 09 36 33](https://user-images.githubusercontent.com/952446/146898120-aabbc3ba-eee9-4e1c-8481-a7f1e6fdf5df.png)

**Comment by yajiv789** [comment] 2021-12-21 10:12
Thanks @thim81  for a quick fix.

**Comment by yajiv789** [comment] 2021-12-21 10:41
@thim81  any tentative date for the next release

**Comment by thim81** [comment] 2021-12-21 11:20
@yajiv789 We are wrapping up the last chorus to do a new release today or tomorrow.

**Comment by thim81** [comment] 2021-12-21 13:33
Closing the issue, since the reported issue is solved in Portman version 1.13.

**Closed by thim81** 2021-12-21 13:33 UTC
